package com.android.loter.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ATTENDACE.
 */
public class Attendace {

    private Long id;
    /** Not-null value. */
    private String time;
    private int type;
    private int projectid;
    private Integer imageid;
    private String imagebase64;
    private String lot;
    private String lat;
    private String address;
    private int projectlocationid;
    private String networkTime;

    public Attendace() {
    }

    public Attendace(Long id) {
        this.id = id;
    }

    public Attendace(Long id, String time, int type, int projectid, Integer imageid, String imagebase64, String lot, String lat, String address, int projectlocationid, String networkTime) {
        this.id = id;
        this.time = time;
        this.type = type;
        this.projectid = projectid;
        this.imageid = imageid;
        this.imagebase64 = imagebase64;
        this.lot = lot;
        this.lat = lat;
        this.address = address;
        this.projectlocationid = projectlocationid;
        this.networkTime = networkTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public int getProjectid() {
        return projectid;
    }

    public void setProjectid(int projectid) {
        this.projectid = projectid;
    }

    public Integer getImageid() {
        return imageid;
    }

    public void setImageid(Integer imageid) {
        this.imageid = imageid;
    }

    public String getImagebase64() {
        return imagebase64;
    }

    public void setImagebase64(String imagebase64) {
        this.imagebase64 = imagebase64;
    }

    public String getLot() {
        return lot;
    }

    public void setLot(String lot) {
        this.lot = lot;
    }

    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public int getProjectlocationid() {
        return projectlocationid;
    }

    public void setProjectlocationid(int projectlocationid) {
        this.projectlocationid = projectlocationid;
    }

    public String getNetworkTime() {
        return networkTime;
    }

    public void setNetworkTime(String networkTime) {
        this.networkTime = networkTime;
    }

}
