package com.android.loter.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.android.loter.db.Attendace;
import com.android.loter.db.ShoppingTrolley;

import com.android.loter.db.AttendaceDao;
import com.android.loter.db.ShoppingTrolleyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig attendaceDaoConfig;
    private final DaoConfig shoppingTrolleyDaoConfig;

    private final AttendaceDao attendaceDao;
    private final ShoppingTrolleyDao shoppingTrolleyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        attendaceDaoConfig = daoConfigMap.get(AttendaceDao.class).clone();
        attendaceDaoConfig.initIdentityScope(type);

        shoppingTrolleyDaoConfig = daoConfigMap.get(ShoppingTrolleyDao.class).clone();
        shoppingTrolleyDaoConfig.initIdentityScope(type);

        attendaceDao = new AttendaceDao(attendaceDaoConfig, this);
        shoppingTrolleyDao = new ShoppingTrolleyDao(shoppingTrolleyDaoConfig, this);

        registerDao(Attendace.class, attendaceDao);
        registerDao(ShoppingTrolley.class, shoppingTrolleyDao);
    }
    
    public void clear() {
        attendaceDaoConfig.getIdentityScope().clear();
        shoppingTrolleyDaoConfig.getIdentityScope().clear();
    }

    public AttendaceDao getAttendaceDao() {
        return attendaceDao;
    }

    public ShoppingTrolleyDao getShoppingTrolleyDao() {
        return shoppingTrolleyDao;
    }

}
