package com.android.loter.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SHOPPING_TROLLEY.
 */
public class ShoppingTrolley {

    private Long id;
    /** Not-null value. */
    private String num;
    /** Not-null value. */
    private String product_id;

    public ShoppingTrolley() {
    }

    public ShoppingTrolley(Long id) {
        this.id = id;
    }

    public ShoppingTrolley(Long id, String num, String product_id) {
        this.id = id;
        this.num = num;
        this.product_id = product_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNum() {
        return num;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNum(String num) {
        this.num = num;
    }

    /** Not-null value. */
    public String getProduct_id() {
        return product_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProduct_id(String product_id) {
        this.product_id = product_id;
    }

}
